### ISSUE TITLE
Rackla is difficult to deploy to staging/production

### ISSUE THREAD

**Issue by beno** [AntonFagerberg/rackla#23] opened 2016-09-15 21:45 UTC
It turns out it needs to be added to the ill-documented `:included_applications` list in `Mixfile.application/0`. Adding `:rackla` to the `:applications` list (as is standard practice for all production dependencies) produces an error. See also [this post of mine on elixirforum](https://elixirforum.com/t/documenting-the-use-of-included-applications/1673/4?u=beno).

**Comment by AntonFagerberg** [comment] 2016-09-15 21:56
Thanks for the report! I'll take a look at it as soon as I can!

**Comment by AntonFagerberg** [comment] 2016-09-16 08:24
(I'm presuming that you are using Rackla as an dependency from Hex. If you have cloned the code, then this is not applicable.)

To start, this is the cause of your error:

When you add `:rackla` as an application to start (which is what my documentation says), Elixir (or Mix) will try to launch [lib/rackla/application.ex](https://github.com/AntonFagerberg/rackla/blob/master/lib/rackla/application.ex), this file is in turn dependent on [lib/rackla/router_gen_server.ex](https://github.com/AntonFagerberg/rackla/blob/master/lib/rackla/router_gen_server.ex) which in turn is dependent on [lib/router.ex](https://github.com/AntonFagerberg/rackla/blob/master/lib/router.ex).

Neither of these three files are packaged into the Rackla package published to Hex. While I could add `application.ex` and `router_gen_server.ex` and ship them off, `router.ex` is something you as the consumer will want to define yourself. Additionally, this whould make Rackla responsible for launching the web-server Cowboy which I don't think is a good approach. (Rackla should be able to co-exist with other projects and not demand anything except having a running instance of `Plug`, `Cowboy` and `Hackney`.)

When you use Rackla as a dependency, your project should be responsible for launching Cowboy and define your own Plug Router. You can do this by creating three files (look at the ones created in Rackla for inspiration or just copy-paste them if you want to):

1. [Application](https://github.com/AntonFagerberg/rackla/blob/master/lib/rackla/application.ex)

2. [Genserver](https://github.com/AntonFagerberg/rackla/blob/master/lib/rackla/router_gen_server.ex)

3. [Router](https://github.com/AntonFagerberg/rackla/blob/master/lib/router.ex)


Include Rackla as a dependency:

```elixir
defp deps do
  [{:rackla, "~> 1.1"}, {:cowboy, "~> 1.0"}]
end
```

Do not start `:rackla` as an application. Instead start `:cowboy`, `:plug` and `:hackney` - and also your own application using `mod:` (replace `Rackla.Application` with whatever your Application module is called):
```
def application do
  [applications: [:logger, :cowboy, :plug, :hackney],  mod: {Rackla.Application, []}]
end
```

I don't think you have to use `included_applications`. I've tested that my approach works without that. However, I'm not familiar with the purpose of `included_applications` so I have to do some reading and get back to you.

Does this make sense to you? Does it seem like a reasonable approach?

**Comment by AntonFagerberg** [comment] 2016-09-16 08:47
I should probably fix so that Rackla can be added to applications as well. However, the steps I wrote above will still be required. Until I release a new version of Rackla, please leave it out of applications :)

**Comment by AntonFagerberg** [comment] 2016-09-16 09:30
(Edited previous messages)

**Comment by AntonFagerberg** [comment] 2016-09-16 11:36
I've committed a test version with a small fix, you can try it by using this as the dependency instead: 

`{:rackla, "~> 1.1", git: "git://github.com/antonfagerberg/rackla.git", branch: "feature/application"}`

Then it should be possible to add `:rackla` to `applications:` as well.

You still need to define your own Router etc as mentioned before.

**Comment by beno** [comment] 2016-09-16 13:28
Hey thanks a lot. I will give it a try asap. To clarify, the problem here is that dependencies need to be explicitly listed in the applications list, even if they are just libraries, and this requirement only applies to building a production release. So even if in *development* all seems fine and the code picks up the dependency from `deps`, it is only *production* this fails **at runtime** because the libraries aren't bundled (even though it does compile). To me this seems highly inconsistent and un-DRY, but people on elixirforum don't seem to mind. So the rule is, whatever you put in deps, you put in applications. Except the `only: :dev` deps of course, but the meaning of that flag has fully escaped me by now.

I will let you know how it goes.

**Comment by AntonFagerberg** [comment] 2016-09-16 20:48
Thanks for the clarification!

I've made some additional progress. The `develop` branch in this repo should now be stripped of all non-library related code. (So you should be able to reference `{:rackla, "~> 1.2", git: "git://github.com/antonfagerberg/rackla.git", branch: "develop"}` now in your code instead).

I moved and refactored the other code, which should serve as a reference implementation of a complete project using Rackla as a library, to this repo: https://github.com/AntonFagerberg/rackla_skeleton

In the end, I think splitting up the project like this was actually kinda nice - more loose coupling. Also, there is apparently a need for me to use it as a library myself to avoid these bugs :)

Hopefully I didn't screw up too much things. If everything looks good and it seems to work for you, I'll make a proper 1.2.0 release soon!

**Closed** 2016-10-05 18:23 UTC
